### PR TITLE
Making reference to XACRO's global

### PR DESCRIPTION
**Pull request by sharif1093**
I guess global referencing is missed in this one, correct elsewhere ...

### CODE REVIEW

**Comment by jlack1987** [comment]
Your pull request is to the Master branch. Is this intended or did you mean to target develop? We have a new release coming out soon, so it's not likely this'll go in as a hotfix to Master, but if this is causing some problem then we can work it into the upcoming release.

**Comment by sharif1093** [comment]
Thanks for your comment. The current version does not cause problems in compilation, while it causes problems if you put one of the XACRO files (let say `valkyrie_sim.xacro`) outside `val_description` and try to use it directly with `xacro.py`.
However, I am using the modified version at the moment and it won't harm me if you fix it later. So if it is required, I can _pull request_ to `develop` instead.

**Comment by jlack1987** [comment]
Actually, make the PR to the release branch release/daria. I will also go in and update all the other xacro file references and make them use the $(find val_description)/* as well.

**Comment by sharif1093** [comment]
Thanks. Since the target branch of the pull requests cannot be modified, I am closing this PR and will create another one to `release/daria`.

**Pull request closed without merging**
